In [2]:
import re
import numpy as np
import pandas as pd 
import itertools
from io import StringIO

In [161]:
def takeStep(m):
    flashCount = 0
    done = False
    m = m+1
    while not done:
        flash = np.where(m>=10)
        inc = []
        for x in range(0,m.shape[0]):
            for y in range(0,m.shape[1]):
                #inner
                if 0 < x < m.shape[0]-1 and 0 < y < m.shape[1]-1:
                    n = np.array([m[x+1,y],m[x-1,y],m[x,y-1],m[x,y+1],m[x+1,y+1],m[x-1,y-1],m[x+1,y-1],m[x-1,y+1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))
                #corner
                if 0 == x  and 0 == y :
                    n = np.array([m[x+1,y],m[x,y+1],m[x+1,y+1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))
                if m.shape[0]-1 == x  and m.shape[1]-1 == y :
                    n = np.array([m[x-1,y],m[x,y-1],m[x-1,y-1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))
                if 0 == x  and m.shape[1]-1 == y :
                    n = np.array([m[x+1,y],m[x,y-1],m[x+1,y-1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))
                if m.shape[0]-1 == x  and 0 == y :
                    n = np.array([m[x-1,y-1],m[x,y+1],m[x-1,y+1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))                    

                # edges 
                if x == 0 and 0 < y < m.shape[1]-1:
                    n = np.array([m[x+1,y],m[x+1,y-1],m[x+1,y+1],m[x,y-1],m[x,y+1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))              
                
                if x == m.shape[1]-1 and 0 < y < m.shape[1]-1:
                    n = np.array([m[x-1,y],m[x-1,y-1],m[x-1,y+1],m[x,y-1],m[x,y+1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))    

                if 0 < x < m.shape[0]-1 and y == 0:
                    n = np.array([m[x+1,y],m[x-1,y],m[x,y+1],m[x-1,y+1],m[x+1,y+1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))    

                if 0 < x < m.shape[0]-1 and y == m.shape[1]-1:
                    n = np.array([m[x+1,y],m[x-1,y],m[x,y-1],m[x+1,y-1],m[x-1,y-1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))    

        flashCount += len(flash[0])
        #print('len flash:',len(flash[0]))
        for i in range(0,len(flash[0])):
            m[flash[0][i],flash[1][i]] = -99

        for i in inc:
            m[i[0]] += i[1]

        if len(flash[1]) == 0:# or runCount == 6:
            done = True 

    m[m < 0] = 0
    return (m,flashCount)

In [167]:
m = np.matrix(np.genfromtxt('2020-11', delimiter=1, dtype=int))
print(m)
print(m.shape)
fcnt = 0

part_b = False
cnt = 0
while not part_b: 
#for i in range(1,196):
    m , flashcnt = takeStep(m)
    fcnt += flashcnt
    cnt += 1
    #print(np.count_nonzero(m == 0))
    if np.count_nonzero(m == 0) == 100:
        part_b = True 
#    if  i < 10 or i ==193 or i == 194 or i == 194:
#        print('After STEP',str(i), ' -- ',fcnt,np.count_nonzero(m == 0))
#        print(m)
print(cnt)

[[5 4 8 3 1 4 3 2 2 3]
 [2 7 4 5 8 5 4 7 1 1]
 [5 2 6 4 5 5 6 1 7 3]
 [6 1 4 1 3 3 6 1 4 6]
 [6 3 5 7 3 8 5 4 7 8]
 [4 1 6 7 5 2 4 6 4 5]
 [2 1 7 6 8 4 1 7 2 1]
 [6 8 8 2 8 8 1 1 3 4]
 [4 8 4 6 8 4 8 5 5 4]
 [5 2 8 3 7 5 1 5 2 6]]
(10, 10)
195


In [153]:
m = np.matrix(np.genfromtxt('2020-11-ex', delimiter=1, dtype=int))
print(m)
print(m.shape)

done_2 = False 
steps = 0
while not done_2:
    steps += 1

    flashCount = 0
    done = False
    m = m+1
    while not done:
        flash = np.where(m>=10)
        inc = []
        for x in range(0,m.shape[0]):
            for y in range(0,m.shape[1]):
                #inner
                if 0 < x < m.shape[0]-1 and 0 < y < m.shape[1]-1:
                    n = np.array([m[x+1,y],m[x-1,y],m[x,y-1],m[x,y+1],m[x+1,y+1],m[x-1,y-1],m[x+1,y-1],m[x-1,y+1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))
                #corner
                if 0 == x  and 0 == y :
                    n = np.array([m[x+1,y],m[x,y+1],m[x+1,y+1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))
                if m.shape[0]-1 == x  and m.shape[1]-1 == y :
                    n = np.array([m[x-1,y],m[x,y-1],m[x-1,y-1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))
                if 0 == x  and m.shape[1]-1 == y :
                    n = np.array([m[x+1,y],m[x,y-1],m[x+1,y-1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))
                if m.shape[0]-1 == x  and 0 == y :
                    n = np.array([m[x-1,y-1],m[x,y+1],m[x-1,y+1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))                    

                # edges 
                if x == 0 and 0 < y < m.shape[1]-1:
                    n = np.array([m[x+1,y],m[x+1,y-1],m[x+1,y+1],m[x,y-1],m[x,y+1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))              
                
                if x == m.shape[1]-1 and 0 < y < m.shape[1]-1:
                    n = np.array([m[x-1,y],m[x-1,y-1],m[x-1,y+1],m[x,y-1],m[x,y+1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))    

                if 0 < x < m.shape[0]-1 and y == 0:
                    n = np.array([m[x+1,y],m[x-1,y],m[x,y+1],m[x-1,y+1],m[x+1,y+1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))    

                if 0 < x < m.shape[0]-1 and y == m.shape[1]-1:
                    n = np.array([m[x+1,y],m[x-1,y],m[x,y-1],m[x+1,y-1],m[x-1,y-1]])
                    if len(n[n>=10]) > 0:
                        inc.append(((x,y),len(n[n>=10])))    

        flashCount += len(flash[0])
        for i in range(0,len(flash[0])):
            m[flash[0][i],flash[1][i]] = -99

        for i in inc:
            m[i[0]] += i[1]

        if len(flash[1]) == 0:# or runCount == 6:
            done = True 

    m[m < 0] = 0
    if len(flash[0]) == 100:
        done_2 = True 

print(steps)

[[5 4 8 3 1 4 3 2 2 3]
 [2 7 4 5 8 5 4 7 1 1]
 [5 2 6 4 5 5 6 1 7 3]
 [6 1 4 1 3 3 6 1 4 6]
 [6 3 5 7 3 8 5 4 7 8]
 [4 1 6 7 5 2 4 6 4 5]
 [2 1 7 6 8 4 1 7 2 1]
 [6 8 8 2 8 8 1 1 3 4]
 [4 8 4 6 8 4 8 5 5 4]
 [5 2 8 3 7 5 1 5 2 6]]
(10, 10)


KeyboardInterrupt: 