In [1]:
import numpy as np
import re
from collections import Counter

In [204]:
file1 = open('input.txt', 'r')
#file1 = open('input.txt', 'r')
Lines = file1.readlines()
bingo_numbers_str = Lines[0].split(',')
bingo_numbers = [int(x) for x in bingo_numbers_str]
boards = []
board = []
board_line_count = 0
for i in range(2,len(Lines)):
    board_line_str = re.findall('\d+',Lines[i].replace('\n','')) 
    board_line_int = []
    for ele in board_line_str:
        board_line_int.append(int(ele))
    if(len(board_line_int)!=0): # and not i == len(Lines)-1):
        #print('if:',i,board_line_int)
        board.append(board_line_int)
    else:
        #print('else:',i,board_line_int)
        boards.append(np.array(board))
        board = []
    #if(i == len(Lines)-1):
    #    print('last if:',i,board_line_int)
    #    boards.append(np.array(board))
    #    board = []

boards.append(np.array(board))
print('boards:',boards)

boards: [array([[30, 46, 94, 20,  2],
       [53, 67, 69, 75, 65],
       [27, 24, 85, 28, 60],
       [57, 58, 42, 36, 78],
       [35, 98, 87, 91, 93]]), array([[72, 71, 91, 73, 19],
       [ 2, 13, 14,  8, 74],
       [42, 34, 31, 56,  9],
       [82, 59, 44, 67, 79],
       [49,  6, 98, 10, 30]]), array([[95, 24, 25, 11, 34],
       [57, 65, 41, 92,  8],
       [91, 26,  1, 62, 38],
       [47, 93,  4, 37,  0],
       [15, 44, 33, 20, 97]]), array([[24, 69, 55,  7, 25],
       [45, 64, 56, 71, 18],
       [94, 10, 62, 19, 36],
       [53, 74, 49, 61, 80],
       [50, 68, 60, 76, 84]]), array([[86, 78, 29,  1, 71],
       [ 2,  9, 24, 34, 96],
       [47, 75, 61, 13, 26],
       [10, 66, 28, 83, 14],
       [91, 63, 45, 76, 50]]), array([[61, 60, 22, 11, 95],
       [25, 81, 13, 15, 53],
       [59, 89, 65, 18, 39],
       [58, 50,  1, 47, 52],
       [48, 16, 29, 75, 56]]), array([[62,  0, 93, 41, 53],
       [69, 47, 29, 50, 46],
       [81,  8, 20, 38, 23],
       [ 4, 64,  5, 37

In [182]:
def evalBoard(bingo_board,bingo_numbers):
    bingo = False
    #print('board',bingo_board,'numbers',bingo_numbers)
    for row in bingo_board:
        bingo_count = 0
        cnt = Counter(row.tolist() + bingo_numbers)
        #print(cnt)
        for ele in cnt.values():
            if(ele > 1):
                bingo_count += 1
                if(bingo_count == 5):
                    bingo = True 
                    print('**** BINGO ****')
                    return [bingo_board,bingo_numbers] 
        #print(bingo_count,row)    
        bingo_count = 0            

    #print('--eval cols--')

    if not bingo:
        for i in range(0,5):
            bingo_count = 0
            col = bingo_board[:,i]
            cnt = Counter(col.tolist() + bingo_numbers)
            for ele in cnt.values():
                if(ele > 1):
                    bingo_count += 1 
                    if(bingo_count == 5):
                        bingo = True 
                        print('**** BINGO ****')
                        return [bingo_board,bingo_numbers] 
            #print(bingo_count,col)    
            bingo_count = 0    

    return None      

In [202]:
def evalLoop(boards):
    result_exp = []

    winlose = []

    for board in boards:
        winlose.append(False)

    for i in range(5,len(bingo_numbers)):
        for k in range(0,len(boards)):
            if(not winlose[k]):
                ele = boards[k]
                result = evalBoard(ele,bingo_numbers[0:i])
                if not result == None: 
                    print(ele,type(ele),bingo_numbers[0:i])
                    winlose[k] = True 
                    result_exp.append(result)
    return result_exp

In [205]:

result_a = evalLoop(boards) 
result = result_a[len(result_a)-1]

#result = evalBoard(boards[2],bingo_numbers[0:12])

print('result_arr       : ',result)
print('last number      : ',result[1][len(result[1])-1])

unmarked = []
for i in range(0,5):
    for k in range(0,5):
        if(not result[0][i][k] in result[1]):
            unmarked.append(result[0][i][k])



print('sum of unmarked  : ',sum(unmarked))
print('final result     : ',sum(unmarked) * result[1][len(result[1])-1])

**** BINGO ****
[[51 18 87 35 55]
 [52 85 79 56 82]
 [83 26 24 29 43]
 [80 76  4 45 13]
 [11 12 99 94 47]] <class 'numpy.ndarray'> [4, 75, 74, 31, 76, 79, 27, 19, 69, 46, 98, 59, 83, 23, 90, 52, 87, 6, 11, 92, 80, 51]
**** BINGO ****
[[69 59 50 48 56]
 [17 61 16 92 47]
 [63 60 62  5  3]
 [37 97 38 83 58]
 [73 18 71 19 94]] <class 'numpy.ndarray'> [4, 75, 74, 31, 76, 79, 27, 19, 69, 46, 98, 59, 83, 23, 90, 52, 87, 6, 11, 92, 80, 51, 43, 5, 94, 17, 15, 67, 25, 30, 48]
**** BINGO ****
[[69 73 42 46 53]
 [ 5 71 50  6 74]
 [14 44 99 62 87]
 [54 84 86 94 21]
 [29 51 38 67  8]] <class 'numpy.ndarray'> [4, 75, 74, 31, 76, 79, 27, 19, 69, 46, 98, 59, 83, 23, 90, 52, 87, 6, 11, 92, 80, 51, 43, 5, 94, 17, 15, 67, 25, 30, 48, 47, 62]
**** BINGO ****
[[97 29 15 61 83]
 [46 69 51 71 17]
 [40 94 49 14 66]
 [52 20 57 62 80]
 [19 72 75 84 36]] <class 'numpy.ndarray'> [4, 75, 74, 31, 76, 79, 27, 19, 69, 46, 98, 59, 83, 23, 90, 52, 87, 6, 11, 92, 80, 51, 43, 5, 94, 17, 15, 67, 25, 30, 48, 47, 62, 71]
***

In [ ]:
#falsche Antwort: 50700

**** BINGO ****


[array([[22, 13, 17, 11,  0],
        [ 8,  2, 23,  4, 24],
        [21,  9, 14, 16,  7],
        [ 6, 10,  3, 18,  5],
        [ 1, 12, 20, 15, 19]]),
 [7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24, 10, 16]]

In [2]:
import pygame, sys
print(pygame.font.get_fonts())

ModuleNotFoundError: No module named 'pygame'