In [17]:
import re
import numpy as np
import pandas as pd 

In [214]:
file1 = open('input.txt', 'r')
#file1 = open('input.txt', 'r')
Lines = file1.readlines()
Lines = [x.replace('\n','') for x in Lines]
#print(Lines)
coordinates = []
max_x = 0
max_y = 0
for ele in Lines: 
    #print(re.findall('\d+',ele))
    matches_arr = re.findall('\d+',ele)
    coordinates.append({'start':(int(matches_arr[0]),int(matches_arr[1])),'end':(int(matches_arr[2]),int(matches_arr[3]))})
    if int(matches_arr[0]) > max_x:
        max_x = int(matches_arr[0])
    if int(matches_arr[3]) > max_x:
        max_x = int(matches_arr[3])
    if int(matches_arr[2]) > max_y:
        max_y = int(matches_arr[2])
    if int(matches_arr[1]) > max_y:
        max_y = int(matches_arr[1])        



print(max_x,max_y)
#matrix = np.zeros((max_x+1, max_y+1))

990 990


In [215]:
matrix = np.zeros((max_x+1, max_y+1))
for ele in coordinates:

#
# LINES
#
    start = ele['start']
    end = ele['end']

    if start[0] == end[0] and start[1] < end[1]:
        #print(ele)
        for i in range(0,end[1]-start[1]+1):
        #    print(i,start[0],start[1]+i)
            matrix[start[0]][start[1]+i] += 1

    if start[0] == end[0] and start[1] > end[1]:
        #print(ele)
        for i in range(0,start[1]-end[1]+1):
        #    print(i,start[0],start[1]-i)
            matrix[start[0]][start[1]-i] += 1     

    if start[1] == end[1] and start[0] < end[0]:
        #print(ele)
        for i in range(0,end[0]-start[0]+1):
        #    print(i,start[0]+i,start[1])
            matrix[start[0]+i][start[1]] += 1    

    if start[1] == end[1] and start[0] > end[0]:
        #print(ele)
        for i in range(0,start[0]-end[0]+1):
        #    print(i,start[0]-i,start[1])
            matrix[start[0]-i][start[1]] += 1                


#
# Diaglonals
#
for ele in coordinates:
    start = ele['start']
    end = ele['end']
    
    if start[0] < end[0] and start[1] > end[1]:
        #print(ele)
        for i in range(0,end[0]-start[0]+1):
        #    print(i,start[0]+i,start[1]-i)
            matrix[start[0]+i][start[1]-i] += 1       
    if start[0] > end[0] and start[1] > end[1]:
        #print(ele)
        for i in range(0,start[0]-end[0]+1):
        #    print(i,start[0]-i,start[1]-i)
            matrix[start[0]-i][start[1]-i] += 1 

    if start[0] < end[0] and start[1] < end[1]:
        #print(ele)
        for i in range(0,end[0]-start[0]+1):
        #    print(i,start[0]+i,start[1]+i)
            matrix[start[0]+i][start[1]+i] += 1   

    if start[0] > end[0] and start[1] < end[1]:
        #print(ele)
        for i in range(0,start[0]-end[0]+1):
        #    print(i,start[0]-i,start[1]+i)
            matrix[start[0]-i][start[1]+i] += 1                                  

print(matrix)            
print(np.count_nonzero(matrix > 1))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
21466


In [154]:
np.count_nonzero(matrix > 1)

19402

In [ ]:

#
# Diaglonals
#
#for ele in coordinates:
#    start = ele['start']
#    end = ele['end']
#    if start[0] < end[0] and start[1] < end[1]:
#        print(ele)
        #for i in range(start[0],end[1]):
        #    matrix[i,i] += 1 
    
    
    
    
    #if start[0] < end[0] and start[1] > end[1]:
    #    #print(ele)
    #    for i in range(0,end[0]-start[0]+1):
    #        matrix[start[0]+i,start[1]-i] += 1       
    #if start[0] > end[0] and start[1] < end[1]:
    #    print(ele)
    #    for i in range(0,end[1]+1):
    #        #print(start[0]-i,start[1]+i)
    #        y = start[1]+i
    #        #if y >= 991:
    #        #    y = 990
    #        #matrix[start[0]-i,y] += 1 
    #    #for i in range(0,end[0]-start[0]+1):
    #    #    matrix[start[0]+i,start[1]-i] += 1    
    #if start[0] > end[0] and start[1] > end[1]:  
    #    #print(ele)
    #    for i in range(0,start[0]-end[0]+1):
    #    #    print(i,start[0]-i,start[1]-i)
    #        matrix[start[0]-i,start[1]-i] += 1