In [1]:
import re
import numpy as np
import pandas as pd 
#import plotly.express as px
import sys
import itertools
from collections import defaultdict, Counter 

In [7]:
file1 = open('input.txt', 'r')
Lines = file1.readlines()
Lines = [x.replace('\n','') for x in Lines]
print(list(Lines[0]))
matrix = []
for line in Lines:
    matrix.append([int(x) for x in list(line)])
matrix_np = np.array(matrix)
print(matrix_np)


#def printBasin(point):
#    return len(set(getSmallesNeighbor(matrix_np_2,point,[])))


def getSmallesNeighbor(matrix,point,basin):
    if not str(point[0])+','+str(point[1]) in basin:
        basin.append(str(point[0])+','+str(point[1]))
        #matrix[point[0]][point[1]] = 9 
        left = matrix[point[0],point[1]-1]
        right = matrix[point[0],point[1]+1]
        up = matrix[point[0]-1,point[1]]
        down = matrix[point[0]+1,point[1]]

        if up < 9:
            basin = getSmallesNeighbor(matrix,(point[0]-1,point[1]),basin )
        if down < 9:
            basin = getSmallesNeighbor(matrix,(point[0]+1,point[1]),basin )
        if right < 9:
            basin = getSmallesNeighbor(matrix,(point[0],point[1]+1),basin )
        if left < 9:
            basin = getSmallesNeighbor(matrix,(point[0],point[1]-1),basin )  
    return basin 

def getSmallesNeighbor_2(matrix,point,visted):
    if point[0] < 0 or point[1] < 0 or point[0] > 99 or point[1] > 99 or point in visted or matrix[point[1],point[0]] == 9:
        return 0, visted  
    result = 1 
    visted.append(point)
    basin, visted = getSmallesNeighbor_2(matrix, (point[0]+1,point[1]),visted)
    result += basin
    basin, visted = getSmallesNeighbor_2(matrix, (point[0]-1,point[1]),visted)
    result += basin
    basin, visted = getSmallesNeighbor_2(matrix, (point[0],point[1]+1),visted)
    result += basin
    basin, visted = getSmallesNeighbor_2(matrix, (point[0],point[1]-1),visted)
    result += basin
    print(result)
    return result,visted

def printBasin(matrix,point):
    basin, matrix  = getSmallesNeighbor(matrix,point,[])
    return (basin, matrix)


result = []

#inner
for i in range(1,len(matrix_np[:][0])-1):
    for k in range(1,len(matrix_np[:][:,0])-1):
        up = matrix_np[k][i-1]
        down = matrix_np[k][i+1]
        left = matrix_np[k-1][i]
        right = matrix_np[k+1][i]
        if matrix_np[k][i] < up and matrix_np[k][i] < down and matrix_np[k][i] < left and matrix_np[k][i] < right:
            result.append((matrix_np[k][i],(i,k)))

#corner 
point = matrix_np[0][0]
print('topleft: ',point)
if point < matrix_np[1][0] and point < matrix_np[0][1]:
    result.append((point,(0,0)))

point = matrix_np[len(matrix_np[:][:,0])-1][len(matrix_np[:][0])-1]
print('bottomright:',point,matrix_np[len(matrix_np[:][:,0])-2][len(matrix_np[:][0])-1] ,matrix_np[len(matrix_np[:][:,0])-1][len(matrix_np[:][0])-2])
if point < matrix_np[len(matrix_np[:][:,0])-2][len(matrix_np[:][0])-1] and point < matrix_np[len(matrix_np[:][:,0])-1][len(matrix_np[:][0])-2]:
    result.append((point,(len(matrix_np[:][:,0])-1,len(matrix_np[:][0])-1)))

point = matrix_np[0][len(matrix_np[:][0])-1]
print('topright:',point,matrix_np[1][len(matrix_np[:][0])-1],matrix_np[0][len(matrix_np[:][0])-2])
if point < matrix_np[0][len(matrix_np[:][0])-2] and point < matrix_np[1][len(matrix_np[:][0])-1]:
    result.append((point,(0,len(matrix_np[:][0])-1)))

point = matrix_np[len(matrix_np[:][:,0])-1][0]
print('bottomleft:',point,matrix_np[len(matrix_np[:][:,0])-1][1],matrix_np[len(matrix_np[:][:,0])-2][0])
if point < matrix_np[len(matrix_np[:][:,0])-1][1] and point < matrix_np[len(matrix_np[:][:,0])-2][0]:
    result.append((point,(len(matrix_np[:][:,0])-1,0)))


#edges
#print('top',matrix_np[0][:])
for i in range(1,len(matrix_np[0][:])-1):
    point = matrix_np[0][i]
    if(point < matrix_np[0][i-1] and point < matrix_np[0][i+1] and point < matrix_np[1][i]):
        result.append((point,(0,i)))

#print('bottom',matrix_np[-1][:])
for i in range(1,len(matrix_np[-1][:])-1):
    point = matrix_np[-1][i]
    if(point < matrix_np[-1][i-1] and point < matrix_np[-1][i+1] and point < matrix_np[-2][i]):
        result.append((point,(len(matrix_np[:][:,0])-1,i)))


#print('left',matrix_np[:][:,0])
for i in range(1,len(matrix_np[:][:,0])-1):
    point = matrix_np[:][:,0][i]
    if point < matrix_np[:][:,0][i+1] and point < matrix_np[:][:,0][i-1] and point < matrix_np[:][:,1][i]:
        result.append((point,(0,i)))

#print('right',matrix_np[:][:,-1],len(matrix_np[:][:,-1]))
for i in range(1,len(matrix_np[:][:,-1])-1):
    point = matrix_np[:][:,-1][i]
    if point < matrix_np[:][:,-1][i-1] and point < matrix_np[:][:,-1][i+1] and point < matrix_np[:][:,-2][i]:
        result.append((point,(len(matrix_np[:][:,-1])-1,i)))
print('......')

finalresult = 0
for ele in result:
    #print(ele)
    finalresult += ele[0]+1
print('final result #1 :',finalresult)
print('-- STEP ### 2 --')

#matrix_np_2 = matrix_np.copy()
#
#matrix_np_2 = np.append(matrix_np, np.full((1, len(matrix_np_2[0])), 9), axis = 0)
#matrix_np_2 = np.append(np.full((1, len(matrix_np_2[0])), 9), matrix_np_2, axis = 0)
#
#append_arr = []
#for i in range(len(matrix_np_2)):
#    append_arr.append([9])
#
#matrix_np_2 = np.append(append_arr, matrix_np_2, axis = 1)
#matrix_np_2 = np.append(matrix_np_2,append_arr, axis = 1)
#

finalresult = 1 
result_2  = [] 

for ele in result: 
    point = (ele[1][0],ele[1][1])
    small_res , visted  = getSmallesNeighbor_2(matrix_np,point,[])
    result_2.append(small_res)


result_2 = np.sort(np.array(result_2))
print(result_2)
print(len(result_2))
finalresult = result_2[-1] * result_2[-2] * result_2[-3]
print('final result #2 :',finalresult)

['8', '6', '5', '4', '4', '3', '4', '7', '8', '9', '4', '3', '2', '4', '4', '6', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '5', '6', '7', '8', '9', '2', '3', '5', '6', '7', '8', '9', '5', '3', '2', '4', '5', '7', '9', '8', '7', '6', '4', '2', '1', '2', '4', '5', '6', '7', '8', '9', '6', '5', '6', '5', '6', '8', '9', '7', '7', '6', '5', '4', '2', '3', '2', '4', '5', '7', '8', '9', '8', '7', '5', '4', '5', '6', '7', '8', '9', '8', '7', '6', '5', '4', '3', '1', '3', '3', '5', '9', '9', '9']
[[8 6 5 ... 9 9 9]
 [8 7 4 ... 8 7 7]
 [9 6 5 ... 9 5 6]
 ...
 [8 7 6 ... 1 2 3]
 [9 8 9 ... 3 4 4]
 [9 9 6 ... 4 6 7]]
topleft:  8
bottomright: 7 4 6
topright: 9 7 9
bottomleft: 9 9 9
......
final result #1 : 439
-- STEP ### 2 --
1
1
2
1
1
3
4
5
6
7
8
11
12
13
14
16
17
1
1
2
1
2
1
4
5
6
7
8
9
10
13
14
15
16
17
1
2
3
1
2
3
4
5
6
7
8
9
1
11
12
16
17
18
19
20
21
39
40
41
42
43
44
46
47
48
49
50
51
52
1
1
1
1
3
4
1
6
7
8
9
10
11
12
13
14
15
16
18
19
20
21
22
23
24
25
1
2
1
4
5
31
32
33
34
35
1
38


In [117]:
# 2502528 --> false 
# 2427250 --> false
# 1520589 --> false
# 929292 --> false 
# 2131344 --> false 
# 3715096 --> false 
# 1071509 --> false 

#### rolf target: 900900
# 1656800 --> false



In [99]:
def getSmallesNeighbor_2(matrix,point,visted):
    if point in visted or matrix[point[0],point[1]] == 9:
        return 0, visted  

    result = 1 
    visted.append(point)

    basin, visted = getSmallesNeighbor_2(matrix, (point[0]+1,point[1]),visted)
    result += basin
    basin, visted = getSmallesNeighbor_2(matrix, (point[0]-1,point[1]),visted)
    result += basin
    basin, visted = getSmallesNeighbor_2(matrix, (point[0],point[1]+1),visted)
    result += basin
    basin, visted = getSmallesNeighbor_2(matrix, (point[0],point[1]-1),visted)
    result += basin

    return result,visted

In [103]:
print(result[2][1])
print(matrix_np_2)
point = (result[2][1][0]+1,result[2][1][0]+1)
print(getSmallesNeighbor_2(matrix_np_2,point,[]))

(0, 1)
[[9 9 9 9 9 9 9 9 9 9 9 9]
 [9 2 1 9 9 9 4 3 2 1 0 9]
 [9 3 9 8 7 8 9 4 9 2 1 9]
 [9 9 8 5 6 7 8 9 8 9 2 9]
 [9 8 7 6 7 8 9 6 7 8 9 9]
 [9 9 8 9 9 9 6 5 6 7 8 9]
 [9 9 9 9 9 9 9 9 9 9 9 9]]
(3, [(1, 1), (2, 1), (1, 2)])


In [108]:
for ele in result:
    print(ele)

(5, (2, 2))
(0, (0, 9))
(1, (0, 1))
(5, (4, 6))


In [110]:
result_2 = []
for ele in result: 
    point = (ele[1][0]+1,ele[1][1]+1)
    small_res , visted  = getSmallesNeighbor_2(matrix_np_2,point,[])
    result_2.append(small_res)


result_2 = np.sort(np.array(result_2))
print(result_2)
finalresult = result_2[-1] * result_2[-2] * result_2[-3]
print('final result #2 :',finalresult)

[ 3  9  9 14]
final result #2 : 1134


In [113]:
matrix_np

array([[8, 6, 5, ..., 9, 9, 9],
       [8, 7, 4, ..., 8, 7, 7],
       [9, 6, 5, ..., 9, 5, 6],
       ...,
       [8, 7, 6, ..., 1, 2, 3],
       [9, 8, 9, ..., 3, 4, 4],
       [9, 9, 6, ..., 4, 6, 7]])

In [114]:
len(matrix_np)

100

In [115]:
def getSmallesNeighbor_2(matrix,point,visted):
    if point[0] < 0 or point[1] < 0 or point[0] > 99 or point[1] > 99 or point in visted or matrix[point[0],point[1]] == 9:
        return 0, visted  

    result = 1 
    visted.append(point)

    basin, visted = getSmallesNeighbor_2(matrix, (point[0]+1,point[1]),visted)
    result += basin
    basin, visted = getSmallesNeighbor_2(matrix, (point[0]-1,point[1]),visted)
    result += basin
    basin, visted = getSmallesNeighbor_2(matrix, (point[0],point[1]+1),visted)
    result += basin
    basin, visted = getSmallesNeighbor_2(matrix, (point[0],point[1]-1),visted)
    result += basin

    return result,visted