In [1]:
import pandas as pd
import re
import matplotlib.pyplot as plt
import numpy as np
import random
from collections import Counter
import itertools
import copy
import networkx as nx

In [2]:
def split(word):
    return [char for char in word]

In [3]:
# Using readlines()
file1 = open('aoc-15-ex', 'r')
file1 = open('aoc-15-ex2', 'r')
file1 = open('aoc-15', 'r')
#file1 = open('input.txt', 'r')
Lines = file1.readlines()
Lines = [[int(y) for y in split(x.replace('\n',''))] for x in Lines]
#print(Lines)
m = np.matrix(Lines)


In [4]:
def getNeighbours(point,matrix):
    r = [(point[0]+1,point[1]) , (point[0],point[1]-1), (point[0],point[1]+1) , (point[0]-1,point[1])]
    r_2 = []
    for ele in r:
        if  (0<=ele[0]<matrix.shape[0] and 0<=ele[1]<matrix.shape[1]):
            r_2.append(ele)
    return r_2

In [7]:
m = m_big


In [8]:
G = nx.DiGraph()
for x in range(0,m.shape[0]):
    for y in range(0,m.shape[1]):
        name = '('+str(x)+','+str(y)+')'
        G.add_node(name,value=m[x,y])

for x in range(0,m.shape[0]):
    for y in range(0,m.shape[1]):      
        name = '('+str(x)+','+str(y)+')'
        neighbours = getNeighbours((x,y),m)  
        for n in neighbours:
            name_1 = '('+str(n[0])+','+str(n[1])+')'
            if not name == name_1:
                G.add_edge(name,name_1,weight=m[n])
##
endPoint = '('+str(m.shape[0]-1)+','+str(m.shape[1]-1)+')'

path = nx.shortest_path(G, source='(0,0)', target=endPoint, weight="weight")
path_weight = nx.path_weight(G, path, weight="weight")
print('result 15a: ',path_weight)


In [6]:
m_big = m
for i in range(0,4):
    m_h = m_big[:,i*10:].copy()
    m_h[m_h == 9] = 0
    m_h += 1
    m_big = np.hstack((m_big, m_h))

for i in range(0,4):
    m_h = m_big[i*10:,:].copy()
    m_h[m_h == 9] = 0
    m_h += 1
    m_big = np.vstack((m_big, m_h))
print(m_big)

[[6 8 5 ... 3 4 3]
 [9 4 2 ... 1 3 5]
 [3 7 9 ... 4 2 2]
 ...
 [6 5 6 ... 9 8 6]
 [2 3 1 ... 1 1 6]
 [3 3 3 ... 2 8 3]]


In [12]:
with open('outfile.txt','wb') as f:
    for line in m_big:
        np.savetxt(f, line, fmt='%.0f')